{
  "formatVersion": "1.1",
  "component": {
    "group": "net.subroh0508.kotlinmaterialui",
    "module": "core",
    "version": "0.7.1-baaahs",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-js",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom-legacy",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.1-baaahs.jar",
          "url": "core-0.7.1-baaahs.jar",
          "size": 421652,
          "sha512": "34ab502a7260a983707b0abc6e68df6490a639341ffc6fb42963c032d58b114902f7fdc31549a505eb0f5df30c5552987b31444d7f324b04f4c3fe430d48bbe2",
          "sha256": "76c78f2bad7d90c43873fc720efba0c9bcc28f1718b684fe2b9e579daf7bfb58",
          "sha1": "d7ea461a71ad02071d2bbcf769df895cd3880da2",
          "md5": "f804efb94f47aa764db83313736f24c4"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-js",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom-legacy",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.1-baaahs.jar",
          "url": "core-0.7.1-baaahs.jar",
          "size": 421652,
          "sha512": "34ab502a7260a983707b0abc6e68df6490a639341ffc6fb42963c032d58b114902f7fdc31549a505eb0f5df30c5552987b31444d7f324b04f4c3fe430d48bbe2",
          "sha256": "76c78f2bad7d90c43873fc720efba0c9bcc28f1718b684fe2b9e579daf7bfb58",
          "sha1": "d7ea461a71ad02071d2bbcf769df895cd3880da2",
          "md5": "f804efb94f47aa764db83313736f24c4"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-js",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom-legacy",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.1-baaahs.klib",
          "url": "core-0.7.1-baaahs.klib",
          "size": 872390,
          "sha512": "af2d33be77503f9f27c22766c441c407737a5fefc60dbd26e7bfd1dad519fad8b0dcbeed7fa71f8872b9d798721d01156aae70e48cb3fcbaf1ab91ee22d3843c",
          "sha256": "c8f0c946e737872d1c692898660de3455a1dd79a3c8f968b7e220ffd3d859fc2",
          "sha1": "cba2d64c2ce5edd70ad19843fec7f1111ebdebc1",
          "md5": "9abb3b6caab34d7f3309af8e824728d4"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html-js",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-react-dom-legacy",
          "version": {
            "requires": "17.0.2-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-css-js",
          "version": {
            "requires": "1.0.0-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin-wrappers",
          "module": "kotlin-extensions",
          "version": {
            "requires": "1.0.1-pre.282-kotlin-1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.7.1-baaahs.klib",
          "url": "core-0.7.1-baaahs.klib",
          "size": 872390,
          "sha512": "af2d33be77503f9f27c22766c441c407737a5fefc60dbd26e7bfd1dad519fad8b0dcbeed7fa71f8872b9d798721d01156aae70e48cb3fcbaf1ab91ee22d3843c",
          "sha256": "c8f0c946e737872d1c692898660de3455a1dd79a3c8f968b7e220ffd3d859fc2",
          "sha1": "cba2d64c2ce5edd70ad19843fec7f1111ebdebc1",
          "md5": "9abb3b6caab34d7f3309af8e824728d4"
        }
      ]
    }
  ]
}
