{
  "formatVersion": "1.1",
  "component": {
    "group": "net.subroh0508.kotlinmaterialui",
    "module": "lab",
    "version": "0.7.1-baaahs",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "net.subroh0508.kotlinmaterialui",
          "module": "core",
          "version": {
            "requires": "0.7.1-baaahs"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lab-0.7.1-baaahs.jar",
          "url": "lab-0.7.1-baaahs.jar",
          "size": 66975,
          "sha512": "bab8decab6caab740fd38f5270ef82d0627ca30a01748fabdf0a447ea0005874af07580c34f074b22042ff56e2859cc1beb989c024725befa0718daabd65f3b7",
          "sha256": "f31d63f6cc20464ba96551856d7fb524f16895bc78355736ca67fd26efd975c5",
          "sha1": "65c58a772987863cae1af67ad8c7530a322b1916",
          "md5": "d08adae31cc5d9d8dbc54c24554435f8"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "net.subroh0508.kotlinmaterialui",
          "module": "core",
          "version": {
            "requires": "0.7.1-baaahs"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lab-0.7.1-baaahs.jar",
          "url": "lab-0.7.1-baaahs.jar",
          "size": 66975,
          "sha512": "bab8decab6caab740fd38f5270ef82d0627ca30a01748fabdf0a447ea0005874af07580c34f074b22042ff56e2859cc1beb989c024725befa0718daabd65f3b7",
          "sha256": "f31d63f6cc20464ba96551856d7fb524f16895bc78355736ca67fd26efd975c5",
          "sha1": "65c58a772987863cae1af67ad8c7530a322b1916",
          "md5": "d08adae31cc5d9d8dbc54c24554435f8"
        }
      ]
    },
    {
      "name": "commonFakeApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "net.subroh0508.kotlinmaterialui",
          "module": "core",
          "version": {
            "requires": "0.7.1-baaahs"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lab-0.7.1-baaahs.klib",
          "url": "lab-0.7.1-baaahs.klib",
          "size": 135008,
          "sha512": "4056768e57c2d18557bf15b9144fc79edd6efc92f3598b93c938d7704fa3f588b18b831ab3b93ff70c597c8474af14ea4d914126a3361dacc234a7a9614de85a",
          "sha256": "0010404b296516d761d6eb7a0ac54bd06a2f21d3c64470bfae15cadaff18d4e6",
          "sha1": "a4af05b392c376454e9fec4c86b655ddd89ee701",
          "md5": "d612be7d99788f0f8f4c2bf1975d3cb5"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "net.subroh0508.kotlinmaterialui",
          "module": "core",
          "version": {
            "requires": "0.7.1-baaahs"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lab-0.7.1-baaahs.klib",
          "url": "lab-0.7.1-baaahs.klib",
          "size": 135008,
          "sha512": "4056768e57c2d18557bf15b9144fc79edd6efc92f3598b93c938d7704fa3f588b18b831ab3b93ff70c597c8474af14ea4d914126a3361dacc234a7a9614de85a",
          "sha256": "0010404b296516d761d6eb7a0ac54bd06a2f21d3c64470bfae15cadaff18d4e6",
          "sha1": "a4af05b392c376454e9fec4c86b655ddd89ee701",
          "md5": "d612be7d99788f0f8f4c2bf1975d3cb5"
        }
      ]
    }
  ]
}
