name: Deploy to MavenCentral

on:
  push:
    tags: [v*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Restore cache of Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Configure GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > release.asc.gpg
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch release.asc.gpg | gpg --import --no-tty --batch --yes
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Configure gradle.properties
        run: |
          echo "${{ secrets.SIGNING_AND_SONATYPE_SECRETS }}" > secrets.gpg
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch secrets.gpg >> gradle.properties
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SIGNING_AND_SONATYPE_SECRETS: ${{ secrets.SIGNING_AND_SONATYPE_SECRETS }}
      - name: Publish to MavenCentral
        run: ./gradlew publish --stacktrace
